### ISSUE TITLE
Email formula ambiguity

### ISSUE THREAD

**Issue by SpectralPixel** [Fhavlonir/YPE-placeholder#2]
On [this page](http://young-pirates.eu/board.html) you state that the general formula for deriving board members' email addresses is `name@young-pirates.eu`. However, this is ambiguous in the following ways:
- It doesn't reveal whether both names or just the surname is required
- It doesn't tell whether accents are included in the email addresses (this is less obvious than you may think)

I suggest you just state the email addresses the appropriate members' names. I don't believe DRY isn't the way to go here.

Thanks for considering :)

**Comment by Fhavlonir** [comment]
I chose to do it that way to avoid automated email harvesting, but that is indeed a good point. I will put together a javascript obfuscation thing tonight, to make sure people can get ahold of us!
